# fly.toml app configuration file generated for iterahero2023 on 2024-05-26T07:18:37+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'iterahero2023'
primary_region = 'sin'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[[services]]
  protocol = 'tcp'
  internal_port = 3000
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 250
    soft_limit = 200

  [[services.tcp_checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '1s'

[[vm]]
  size = 'shared-cpu-1x'
