# fly.toml app configuration file generated for iterahero2023 on 2023-11-20T15:22:35+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "iterahero2023"
primary_region = "sin"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[http_service.concurrency]
  type = "connections"
  hard_limit = 200
  soft_limit = 200
