# fly.toml app configuration file generated for iterahero2023 on 2023-12-13T17:32:09+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "iterahero2023"
primary_region = "sin"

[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]

   [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 250
    soft_limit = 200

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

